#server:
#  port: 8082
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  application:
#    name: "DEPARTMENT-SERVICE"
#
#  datasource:
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/department
#    password: 'google'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: 'true'
#    hibernate:
#      ddl-auto: update



spring:
  application:
    name: "DEPARTMENT-SERVICE"
  config:
    import: 'optional:configserver:http://localhost:8888'

